In [3]:
#1. Mendefinisikan State 
 
# Definisi Matrik Transisi (states)

states = ('Rainy', 'Sunny')
 
# definisi Matriks Observasi / Matrik emmisi    
observations = ('walk', 'shop', 'clean')

# definisi Matriks Priority
start_probability = {'Rainy': 0.6, 'Sunny': 0.4}
 
transition_probability = {
   'Rainy' : {'Rainy': 0.7, 'Sunny': 0.3},
   'Sunny' : {'Rainy': 0.4, 'Sunny': 0.6},
   }
 
emission_probability = {
   'Rainy' : {'walk': 0.1, 'shop': 0.4, 'clean': 0.5},
   'Sunny' : {'walk': 0.6, 'shop': 0.3, 'clean': 0.1},
   }

In [4]:
#2. Instalasi library dan representasi pada matrik 

# Library untuk HMM
# Cara install pip install hmmlearn==0.2.2

from hmmlearn import hmm
import numpy as np

model = hmm.MultinomialHMM(n_components=2)
model.startprob_ = np.array([0.6, 0.4])
model.transmat_ = np.array([[0.7, 0.3],
                            [0.4, 0.6]])
model.emissionprob_ = np.array([[0.1, 0.4, 0.5],
                                [0.6, 0.3, 0.1]])

In [5]:
#3. Menyelesaikan permasalahan 1 dari HMM 

# Given a known model what is the likelihood of sequence O happening?
# The probability of the first observation being “Walk” equals to the multiplication 
# of the initial state distribution and emission probability matrix.
# 0.6 x 0.1 + 0.4 x 0.6 = 0.30 (30%). 
# The log likelihood is provided from calling .score.
# catatan {'walk', 'shop','clean' }
# Kasus untuk initial state #
# contoh untuk observasi 'walk' 
# peluang dari model jika observasi adalah 'walk'
# 0.6 x 0.1 + 0.4 x 0.6 = 0.30 (30%)

import math 
math.exp(model.score(np.array([[0]])))

# contoh untuk observasi 'shop' 
# peluang dari model jika observasi adalah 'shop'
# 0.6 x 0.4 + 0.4 x 0.3 = (36%)

math.exp(model.score(np.array([[1]])))

0.36000000000000004

In [6]:
# contoh untuk observasi 'clean' 
# peluang dari model jika observasi adalah 'clean'
# 0.6 x 0.5 + 0.4 x 0.1 = (34%) 

math.exp(model.score(np.array([[2]])))

0.3400000000000001

In [7]:
# contoh untuk observasi {'clean', 'clean'} 
# peluang dari model jika observasi {'clean', 'clean'} adalah

math.exp(model.score(np.array([[2,2]])))

0.1244

In [8]:
#4. Menyelesaikan permaslahan 2 dai HMM dengan viterbi algorithm  

#==== HMM decode dengan algoritma viterbi di dalamnya ======# 
logprob, seq = model.decode(np.array([[1,2,0]]).transpose())
print(math.exp(logprob))
print(seq)

0.015120000000000003
[0 0 1]


In [9]:
logprob, seq = model.decode(np.array([[2,2,2]]).transpose())
print(math.exp(logprob))
print(seq)

0.03674999999999999
[0 0 0]


In [10]:
# 1. peluang dari model jika observasi {'clean', 'clean',’walk’, ‘walk’, ‘shop’} adalah

math.exp(model.score(np.array([[2, 2, 0, 0, 1]])))

0.004082395400000001

In [11]:
# 2. Catat state yang paling  baik untuk untuk observasi {'clean', 'clean',’walk’, ‘walk’,‘shop’} dari model yang ada

logprob, seq = model.decode(np.array([[2, 2, 0, 0, 1]]).transpose())
print(math.exp(logprob))
print(seq)

0.001224720000000001
[0 0 1 1 1]
